version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/node:10.16.3 
      steps:
        - checkout 
        - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
        - run: npm install
        - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
        - run: mysql -e 'CREATE DATABASE IF NOT EXISTS ac_twitter_workspace_test default character set utf8mb4 collate utf8mb4_unicode_ci;'
        - run: npm install sequelize-cli -g
        - run: sequelize db:migrate
        - run:
          name: test
          command: npm test